### ISSUE TITLE
Uncaught error when `.gitignore` isn't present

### ISSUE THREAD

**Issue by anmolm96** [lintrule/lintrule#12]
An uncaught error is thrown when a repo doesn't have a `.gitignore` file:
```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2): readfile '.gitignore'
    at async Object.readTextFile (ext:deno_fs/30_fs.js:754:18)
    at async walkTextFiles (file:///Users/evan/dev/src/flaque/lintrule/cli/walkTextFiles.ts:78:30)
    at async checkRulesAgainstDiff (file:///Users/evan/dev/src/flaque/lintrule/cli/cmds/check/cmd.ts:81:22)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:696:13)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:584:20)
    at async file:///Users/evan/dev/src/flaque/lintrule/cli/main.ts:43:1
```

Can take a stab at fixing this tomorrow, assume it's just wrapping some LOCs in a try/catch block?

**Comment by Flaque** [comment]
fixed!
