### ISSUE TITLE
Throws an error on recently renamed files

### ISSUE THREAD

**Issue by rattrayalex** [lintrule/lintrule#5]
I tried `rules init; rules check` on my `main` branch, and the most recent commit had had some files moved; pretend one of them was `foo/README.md`

I got this stacktrace:

```
➜  rules check                                    

$ git diff HEAD^
error: Uncaught (in promise) NotFound: No such file or directory (os error 2): readfile 'foo/README.md'
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async Object.readFile (ext:deno_fs/30_fs.js:684:18)
    at async getChangesAsFiles (file:///Users/evan/dev/src/flaque/lintrule/cli/git.ts:164:19)
    at async checkCmd (file:///Users/evan/dev/src/flaque/lintrule/cli/cmds/check.ts:51:26)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:696:13)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:584:20)
    at async file:///Users/evan/dev/src/flaque/lintrule/cli/main.ts:22:1
```

I'll note it's a bit odd to find your name in the stacktrace 😄 it was also a bit of a bummer to not see local filepaths in the stacktrace that I could use to try to debug. 

My workaround was to add a dummy commit on top of that.

**Comment by Flaque** [comment]
Thank you for reporting! Can you try this again after running `rules upgrade`, I believe this is fixed now.

**Comment by rattrayalex** [comment]
Nice, thanks for doing this! Sorry, I don't think I'll be able to easily repro, but let's assume fixed and close for now!
